// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuDoX_4fH5C6wm-xj9l1r9lz97oGnie4',
    appId: '1:1047440854342:web:50ae933aad48ff51a26947',
    messagingSenderId: '1047440854342',
    projectId: 'nhom11-qlthuchi',
    authDomain: 'nhom11-qlthuchi.firebaseapp.com',
    storageBucket: 'nhom11-qlthuchi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEWnAgHOCuLa97kL1hwjLG_0WMY67HWig',
    appId: '1:1047440854342:android:35238afb11f090cea26947',
    messagingSenderId: '1047440854342',
    projectId: 'nhom11-qlthuchi',
    storageBucket: 'nhom11-qlthuchi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx4MUECz8kZii1Y6RhLUSsu5WBCzeuLcI',
    appId: '1:1047440854342:ios:3b6466063e13f142a26947',
    messagingSenderId: '1047440854342',
    projectId: 'nhom11-qlthuchi',
    storageBucket: 'nhom11-qlthuchi.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceManagementApp',
  );
}
